# Environment Settings
gpu_id: '0'                     # (str) The id of GPU device(s).
worker: 4                       # (int) The number of workers processing the data.
use_gpu: True                   # (bool) Whether or not to use GPU.
seed: 2024                      # (int) Random seed.
state: INFO                     # (str) Logging level.
reproducibility: True           # (bool) Whether or not to make results reproducible.
data_path: 'dataset/'           # (str) The path of input dataset.
checkpoint_dir: 'saved'         # (str) The path to save checkpoint file.
save_dataset: True             # (bool) Whether or not to save filtered dataset.
dataset_save_path: ~            # (str) The path of saved dataset.
shuffle: True                   # (bool) Whether or not to shuffle the training data before each epoch.
uid_name: 'user'
iid_name: 'item'
inter_name: 'rating'
time_name: 'timestamp'

# Training Settings
epochs: 150                     # (int) The number of training epochs.
batch_size: 128                 # (int) batch size.
learner: adam                   # (str) The name of used optimizer.
learning_rate: 0.001            # (float) Learning rate.

weight_decay: 0.0               # (float) The weight decay value (L2 penalty) for optimizers.

# Evaluation Settings
metrics: ["MRR","NDCG","HR"]  # (list or str) Evaluation metrics.
topk: [10]                      # (list or int or None) The value of k for topk evaluation metrics.
valid_metric: MRR@10            # (str) The evaluation metric for early stopping. 